version: '3.7'
services:
  redis:
    image: redis
    container_name: regulomix_redis
    expose:
      - '6379'
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - regulomix
    restart: always
    sysctls:
      net.core.somaxconn: '511'

  db:
    restart: always
    image: postgres:10
    env_file: .env
    volumes:
      - /Users/suzanaporto/Documents/Códigos/Python/postgres:/var/lib/postgresql/data # trocar o caminho /home/regulomix/postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    networks:
      - regulomix

  gentelella:
    restart: always
    env_file: .env
    build: .
      # context: .
      # dockerfile: Dockerfile
    command: "gunicorn --config gunicorn.py gentelella:app"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - regulomix
    volumes:
      - .:/code
      - ./log:/code/log

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: "celery worker -A gentelella.celery -c 3 --autoscale=10,3 --loglevel=info"
    # user: nobody
    links:
      - redis
    depends_on: 
      - redis
    networks:
      - regulomix
    restart: always
    volumes:
      - .:/code
      - ./log:/code/log
  # commented nginx

networks:
  regulomix:
    driver: bridge