version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: bridge
    restart: always

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env_production
    command: "celery worker -A gentelella.celery -c 3 --autoscale=10,3 --loglevel=info"
    # user: nobody
    links:
      - redis
    depends_on: 
      - redis
    network_mode: bridge
    restart: always
    volumes:
      - .:/code
      - ./log:/code/log

  db:
    restart: always
    image: postgres:10
    env_file: .env_production
    volumes:
      - /home/regulomix/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    network_mode: bridge

  gentelella:
    restart: always
    env_file: .env_production
    build: .
    ports:
      - "5000:5000"
    network_mode: bridge
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
      - ./log:/code/log
