version: '3'
services:
  db:
    restart: always
    image: postgres:10
    env_file: .env_production
    volumes:
      - /Users/suzanaporto/Documents/Códigos/Python/postgres:/var/lib/postgresql/data # trocar o caminho /home/regulomix/postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    network_mode: bridge
  gentelella:
    restart: always
    env_file: .env_production
    build: .
    ports:
      - "5000:5000"
    network_mode: bridge
    depends_on:
      - db
