version: '3'
services:
  redis:
    image: redis
    container_name: regulomix_redis
    expose:
      - '6379'
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    # network_mode: bridge
    networks:
      - regulomix
    restart: always
    sysctls:
      net.core.somaxconn: '511'

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env_production
    command: "celery worker -A gentelella.celery -c 3 --autoscale=10,3 --loglevel=info"
    # user: nobody
    links:
      - redis
    depends_on: 
      - redis
    # network_mode: bridge
    networks:
      - regulomix
    restart: always
    volumes:
      - .:/code
      - ./log:/code/log

  db:
    restart: always
    image: postgres:10
    env_file: .env_production
    volumes:
      - /home/regulomix/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    # network_mode: bridge
    networks:
      - regulomix

  gentelella:
    restart: always
    env_file: .env_production
    build: 
      context: .
      dockerfile: Dockerfile
    command: "gunicorn --config gunicorn.py gentelella:app"
    ports:
      - "5000:5000"
    # network_mode: bridge
    networks:
      - regulomix
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
      - ./log:/code/log

networks:
  regulomix:
    driver: bridge
