version: '3.7'
services:
  db:
    restart: always
    image: postgres:10
    env_file: .env
    volumes:
      - /Users/suzanaporto/Documents/Códigos/Python/postgres:/var/lib/postgresql/data # trocar o caminho /home/regulomix/postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    networks:
      - regulomix
    # network_mode: bridge
  gentelella:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    # network_mode: bridge
    depends_on:
      - db
    networks:
      - regulomix
    # volumes:
    #   - .:.
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    # network_mode: bridge
    networks:
      - regulomix
    depends_on:
      - gentelella

networks:
  regulomix:
    driver: bridge